import pandas as pd
import json
import os
from pathlib import Path
from typing import List

# --- CONFIGURATION ---
# The directory where your downloaded CSV files are stored
INPUT_DATA_DIR = 'autocomplete_data'
# The path to your Vue project's data directory
OUTPUT_JS_FILE = 'src/data/autocomplete.js'

# File names you expect to process
FILE_CONFIG = {
    "ARCHETYPES": f"{INPUT_DATA_DIR}/archetypes.csv",
    "CARD_NAMES": f"{INPUT_DATA_DIR}/card_names.csv",
    "TOURNAMENT_NAMES": f"{INPUT_DATA_DIR}/tournament_names.csv"
}


def get_csv_data_local(file_path: str) -> List[str]:
    """Reads a single column CSV file from the local disk and returns a clean list."""

    file = Path(file_path)
    if not file.exists():
        print(f"ERROR: File not found at {file_path}")
        return []

    try:
        # Use pandas to read the CSV file
        # We assume the data is in the first column (index 0)
        df = pd.read_csv(file)

        # Extract values from the first column, handle missing values, clean whitespace, and convert to list
        data_list = df.iloc[:, 0].dropna().astype(str).str.strip().tolist()

        print(f"Successfully read {len(data_list)} items from {file.name}")
        return data_list

    except Exception as e:
        print(f"An error occurred while processing {file.name}: {e}")
        return []


def generate_js_file(data_dict: dict):
    """Writes the data dictionary to the required JavaScript file format."""

    # 1. Format the data into JavaScript array strings
    js_content_parts = []

    for var_name, data_list in data_dict.items():
        # json.dumps ensures proper JavaScript array formatting and string escaping
        js_array = json.dumps(data_list, indent=4)
        js_content_parts.append(f"export const {var_name} = {js_array};")

    # 2. Construct the final JS content
    js_content = f"""
// This file was automatically generated by generate_autocomplete_data.py
// Do not edit this file manually.

{'\n\n'.join(js_content_parts)}
"""

    # 3. Write to file
    output_path = Path(OUTPUT_JS_FILE)
    os.makedirs(output_path.parent, exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(js_content)

    print(f"\nSuccessfully generated and saved data to {OUTPUT_JS_FILE}")


# --- MAIN EXECUTION ---
if __name__ == "__main__":

    final_data = {}

    # 1. Process all required files
    for var_name, file_path in FILE_CONFIG.items():
        data = get_csv_data_local(file_path)

        if data:
            final_data[var_name] = data

    # 2. Check if any data was processed
    if not final_data:
        print("Fatal Error: No data was successfully processed. Check file paths and contents.")
    else:
        # 3. Generate the JavaScript file
        generate_js_file(final_data)
